---
- include_tasks: load-single-image.yml
  with_items:

  - image_name: 'influxdb'
    image_tag: '1.7.9'
    image_tgz: 'influxdb_1.7.9.tar.bz2'

  - image_name: 'chronograf'
    image_tag: '1.8.7'
    image_tgz: 'chronograf_1.8.7.tar.bz2'

  loop_control:
    loop_var: item
