version: '2'

services:
  modbus-tcp-server:
    image: gitlab.snsi.iii.org.tw:4567/qi/registry/debian8.armhf/modbus-tcp-server
    container_name: modbus-tcp-server
    network_mode: "host"
    environment:
    - MODBUS_TCP_SERVER_HOST=0.0.0.0
    - MODBUS_TCP_SERVER_PORT=1502
    - MODBUS_TCP_SERVER_DATA_LENGTH=200
    - MODBUS_TCP_SERVER_UPDATE_FREQUENCY_SEC=3
