---
- name: Setting for ubuntu platform
  hosts: all
  become: true
  strategy: free
  roles:
  - role: Install-deb-packages
  - role: Generate-Document-by-Right-Clicking
  - role: Set-timezone
  - role: Fcitx-setting
  - role: Place-DLMC-tool
  - role: Place-iSMART-tool
  - role: Place-mkmp-tool
  - role: NTPdate-hwclock-writeback
  - role: Autoremove-deb-packages
  - role: reboot
