{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "coils_01",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  coils_01\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40001",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40001\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40001",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40001\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "coils_02",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  coils_02\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40002",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40002\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40002",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40002\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "coils_03",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  coils_03\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40003",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40003\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Holding_40003",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(time),\r\n  Holding_40003\r\nFROM\r\n  Modbus\r\nWHERE\r\n  $__timeFilter(time)"
    }
   ]
  }
 ]
}