{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "工單",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "工單",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"barcode\" FROM \"reading\".\"rrp\".\"barcode-scanner\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y010\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y0\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y001\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y002\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y003\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y004\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 6",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y005\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 7",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y006\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot 8",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Y007\" FROM \"reading\".\"rrp\".\"Mitsubishi\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "工單",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "工單",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"barcode\" FROM \"reading\".\"rrp\".\"barcode-scanner\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "生產片數",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"reading\".\"rrp\".\"loader\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "總片數",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "alias": "X1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_count\" FROM \"reading\".\"rrp\".\"loader\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "溫度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT temperature FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "濕度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT humidity FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CO2 FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CO_Concentration FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "溫度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \ttemperature FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \tTemperature FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "濕度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \tHumidity FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \thumidity FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Depth",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Water_Depth\" FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Depth",
   "type": "graph",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 27 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Water Depth",
     "groupBy": [
      { "params": [ "did" ], "type": "tag" }
     ],
     "measurement": "DC_[[domain]]",
     "query": "SELECT Water_Depth FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "$dc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CO2 FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Water Depth",
     "groupBy": [
      { "params": [ "did" ], "type": "tag" }
     ],
     "measurement": "DC_[[domain]]",
     "query": "SELECT CO2 FROM \"reading\".\"rrp\".\"Air_Quality_Sensor\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "$dc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "CO",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CO_Concentration FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Water Depth",
     "groupBy": [
      { "params": [ "did" ], "type": "tag" }
     ],
     "measurement": "DC_[[domain]]",
     "query": "SELECT CO_Concentration FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "$dc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CO2_Concentration FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Water Depth",
     "groupBy": [
      { "params": [ "did" ], "type": "tag" }
     ],
     "measurement": "DC_[[domain]]",
     "query": "SELECT CO2_Concentration FROM \"reading\".\"rrp\".\"Modbus-TCP\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "$dc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  }
 ]
}