{
 "title": "機台績效",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "panels": [
  { "title": "稼動", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "開機時間",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power_on_tag\" FROM \"fx5u_event\"  Where \"power_on_tag\" = 1 ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "機台啟動紀錄",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "狀態",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power_on_tag\" FROM \"fx5u_event\"  Where $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "關機時間",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power_on_tag\" FROM \"fx5u_event\"  Where \"power_on_tag\" = 0 ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "昨日稼動",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ( last(\"fx5u_utilization\") / ( last(fx5u_power_on_time) + last(fx5u_power_off_time) ) ) * 100 FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "一週稼動率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "稼動率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"fx5u_utilization\") / (last(fx5u_power_on_time) + last(fx5u_power_off_time))) * 100 FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"fx5u_utilization\") / (last(fx5u_power_on_time) + last(fx5u_power_off_time))) * 100  FROM \"work_time\" WHERE $timeFilter   GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "當日機台上電時間",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (fx5u_power_on_time + fx5u_power_off_time)  FROM \"work_time\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "一週機台上電時間",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(fx5u_power_on_time) + last(fx5u_power_off_time))  FROM \"work_time\" WHERE $timeFilter GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "生產時間",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fx5u_utilization\"  FROM \"work_time\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "一週生產時間",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "生產時間",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fx5u_utilization\") FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "產能", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "昨日產量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 25 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每小時生產片數",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "生產片數",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"count\") - min(\"count\") FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "今日產量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"work_time\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "一週生產片數",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "生產片數",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM \"work_time\" WHERE $timeFilter  GROUP BY time(1d) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "異常", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Level A Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "啟動",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"coils_01\" FROM \"fx5u\" WHERE $timeFilter AND coils_01 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Level B Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 39 },
   "targets": [
    {
     "alias": "水壓",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Water_Pressure\" FROM \"fx5u\" WHERE $timeFilter AND Water_Pressure = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Level C Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 39 },
   "targets": [
    {
     "alias": "水位深度",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Water_Depth\" FROM \"fx5u\" WHERE $timeFilter AND Water_Depth = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "異常統計表(1 hour)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "啟動",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"coils_01\")  as coils_01\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    coils_01 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "水壓",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"Water_Pressure\")  as Water_Pressure\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    Water_Pressure = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "水深",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"Water_Depth\")  as Water_Depth\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    Water_Depth = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "異常統計表(8 hour)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "alias": "啟動",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"coils_01\")  as coils_01\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    coils_01 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "水壓",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"Water_Pressure\")  as Water_Pressure\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    Water_Pressure = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "水深",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"Water_Depth\")  as Water_Depth\nFROM\n    \"fx5u\"\nWHERE\n    $timeFilter AND\n    Water_Depth = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}