{
 "title": "久允工業_KWCT",
 "time": { "from": "2018-12-25T04:00:00.000Z", "to": "2018-12-27T03:59:59.998Z" },
 "panels": [
  { "title": "銑齒機", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "銑齒機三色燈",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_3\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "銑齒機3色燈",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_3\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "銑齒機每日稼動",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    daily_last_total_utilization_hours AS total_utilization_hours,\n    24 - daily_last_total_utilization_hours AS untotal_utilization_hours,\n    daily_last_total_utilization_hours / 8 AS utilization_8_hours_percent,\n    daily_last_total_utilization_hours / 12 AS utilization_12_hours_percent,\n    daily_last_total_utilization_hours / 16 AS utilization_16_hours_percent\nFROM (\n    SELECT\n        LAST(TodayOEE_1) AS daily_last_total_utilization_hours\n    FROM Siemens\n    GROUP BY time(1d, -8h)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "銑齒機今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"TodayOEE_1\" FROM \"reading\".\"rrp\".\"Siemens\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "銑齒機今日稼動",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "銑齒機今日稼動",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"TodayOEE_1\" FROM \"reading\".\"rrp\".\"Siemens\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "油壓",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 18, "x": 5, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"30003\") FROM \"Modbus\" \nWHERE \"30003\" > 300 and $timeFilter GROUP BY time(1h, -8h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "裁斷機(01)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "裁斷機(01)三色燈",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_1\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "裁斷機(01)三色燈",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "裁斷機(01)三色燈",
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_1\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "裁斷機(01)每日稼動",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    daily_last_total_utilization_hours AS total_utilization_hours,\n    24-  daily_last_total_utilization_hours AS untotal_utilization_hours,\n    daily_last_total_utilization_hours / 8 AS utilization_8_hours_percent,\n    daily_last_total_utilization_hours / 12 AS utilization_12_hours_percent,\n    daily_last_total_utilization_hours / 16 AS utilization_16_hours_percent\nFROM (\n    SELECT\n        LAST(total_utilization_hours) AS daily_last_total_utilization_hours\n    FROM FX3G_utilization\n    GROUP BY time(1d, -8h)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "裁斷機(01)今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"FX3G_utilization\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "裁斷機(01)今日稼動",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 38 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "裁斷機(01)今日稼動",
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"FX3G_utilization\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "空壓值監控(>4 平均)",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 1, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"30003\") FROM \"Modbus-1\" \nWHERE \"30003\" > 4 and $timeFilter GROUP BY time(2h, -8h) fill(null) \n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "氣壓值(max)",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 14, "x": 9, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"30003\") FROM \"Modbus-1\" \nWHERE \"30003\" > 4.5 and $timeFilter GROUP BY time(1h, -8h) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "氣壓值(>4 平均)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 50 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"30003\") FROM \"Modbus-1\" \nWHERE \"30003\" > 4 and $timeFilter GROUP BY time(1h, -8h) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "氣壓值",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"30003\" FROM \"Modbus-1\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "裁斷機(03)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "裁斷機(03)三色燈",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_2\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "裁斷機(03)三色燈",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "裁斷機(03)三色燈",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"healthiness\" FROM \"reading\".\"rrp\".\"GYR_light_2\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "裁斷機(03)每日稼動",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    daily_last_total_utilization_hours AS total_utilization_hours,\n    24 - daily_last_total_utilization_hours AS untotal_utilization_hours,\n    daily_last_total_utilization_hours / 8 AS utilization_8_hours_percent,\n    daily_last_total_utilization_hours / 12 AS utilization_12_hours_percent,\n    daily_last_total_utilization_hours / 16 AS utilization_16_hours_percent\nFROM (\n    SELECT\n        LAST(total_utilization_hours) AS daily_last_total_utilization_hours\n    FROM Cutter_Line_2_utilization\n    GROUP BY time(1d, -8h)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "裁斷機(03)今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Cutter_Line_2_utilization\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "裁斷機(03)今日稼動",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 72 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "裁斷機(03)今日稼動",
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Cutter_Line_2_utilization\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  { "title": "真空爐(95)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "每日稼動",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    daily_last_total_utilization_hours AS total_utilization_hours,\n    24 - daily_last_total_utilization_hours AS untotal_utilization_hours,\n    daily_last_total_utilization_hours / 8 AS utilization_8_hours_percent,\n    daily_last_total_utilization_hours / 12 AS utilization_12_hours_percent,\n    daily_last_total_utilization_hours / 16 AS utilization_16_hours_percent\nFROM (\n    SELECT\n        LAST(total_utilization_hours) AS daily_last_total_utilization_hours\n    FROM Q00_utilization\n    GROUP BY time(1d, -8h)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "真空爐(95)今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 87 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Q00_utilization\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "真空爐(95)今日稼動",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 87 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "今日稼動",
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Q00_utilization\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"PRO-COM-RUN\" FROM \"reading\".\"rrp\".\"Q00\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "真空爐(96)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "每日稼動",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    daily_last_total_utilization_hours AS total_utilization_hours,\n    24 - daily_last_total_utilization_hours AS untotal_utilization_hours,\n    daily_last_total_utilization_hours / 8 AS utilization_8_hours_percent,\n    daily_last_total_utilization_hours / 12 AS utilization_12_hours_percent,\n    daily_last_total_utilization_hours / 16 AS utilization_16_hours_percent\nFROM (\n    SELECT\n        LAST(total_utilization_hours) AS daily_last_total_utilization_hours\n    FROM Q00U_utilization\n    GROUP BY time(1d, -8h)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "真空爐(96)今日稼動",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 102 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Q00U_utilization\" where $timeFilter order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "真空爐(96)今日稼動",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 102 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "今日稼動",
     "channel": "select channel",
     "feed": "select feed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total_utilization_hours\" FROM \"reading\".\"rrp\".\"Q00U_utilization\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "CWMS"
    }
   ]
  },
  {
   "title": "細抽ON",
   "type": "graph",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"MECHANICAL-BOOSTER-PUMP-OPERATION\" FROM \"reading\".\"rrp\".\"Q00U\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "三相平均電流",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"40295\") / 1000000000 FROM \"Power_meter\" WHERE \"40295\" > 0  and $timeFilter GROUP BY time(1m, -8h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alarm列表", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 18, "y": 113 } }
 ]
}