---
- name: Copy iSMART 32 TOOL
  copy:
    src: "{{ role_path }}/files/iSMART_32"
    dest: /home/ubuntu/
    mode: 0777
    owner: ubuntu
    group: ubuntu

- name: Copy iSMART 64 TOOL
  copy:
    src: "{{ role_path }}/files/iSMART_64"
    dest: /home/ubuntu/
    mode: 0777
    owner: ubuntu
    group: ubuntu