---

- name: Create tool package file
  file:
    path: "{{ FILE_PATH }}package_tool/"
    state: directory
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy code deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/code_1.77.3-1681292746_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy fcitx deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fcitx_1%3a4.2.9.8-5_all.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy fcitx-chewing deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fcitx-chewing_0.2.3-1_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy google chrome deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/google-chrome-stable_current_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy gparted deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/gparted_1.3.1-1ubuntu1_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy htop deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/htop_3.0.5-7build2_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy net-tools deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/net-tools_1.60+git20181103.0eebece-1ubuntu5_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy nvme-cli deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nvme-cli_1.16-3ubuntu0.1_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy smartmontools deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/smartmontools_7.2-1build2_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy terminator deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/terminator_2.1.1-1_all.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy vim deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/vim_2%3a8.2.3995-1ubuntu2.16_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy fio deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fio_3.28-1_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy hdparm deb package
  ansible.builtin.copy:
    src: "{{ role_path }}/files/hdparm_9.60+ds-1build3_amd64.deb"
    dest: "{{ FILE_PATH }}package_tool"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# - name: Unarchive google chrome
#   unarchive:
#     src: "{{ FILE_PATH }}package_tool/google-chrome.tar.gz"
#     dest: "{{ FILE_PATH }}package_tool"
#     remote_src: yes

- name: Install code package
  apt:
    deb: "{{ FILE_PATH }}package_tool/code_1.77.3-1681292746_amd64.deb"
  ignore_errors: true

- name: Install fcitx package
  apt:
    deb: "{{ FILE_PATH }}package_tool/fcitx_1%3a4.2.9.8-5_all.deb"
  ignore_errors: true

- name: Install fcitx-chewing package
  apt:
    deb: "{{ FILE_PATH }}package_tool/fcitx-chewing_0.2.3-1_amd64.deb"
  ignore_errors: true

- name: Install google-chrome package
  apt:
    deb: "{{ FILE_PATH }}package_tool/google-chrome-stable_current_amd64.deb"
  ignore_errors: true

- name: Install gparted package
  apt:
    deb: "{{ FILE_PATH }}package_tool/gparted_1.3.1-1ubuntu1_amd64.deb"
  ignore_errors: true

- name: Install htop package
  apt:
    deb: "{{ FILE_PATH }}package_tool/htop_3.0.5-7build2_amd64.deb"
  ignore_errors: true

- name: Install net-tools package
  apt:
    deb: "{{ FILE_PATH }}package_tool/net-tools_1.60+git20181103.0eebece-1ubuntu5_amd64.deb"
  ignore_errors: true

- name: Install nvme-cli package
  apt:
    deb: "{{ FILE_PATH }}package_tool/nvme-cli_1.16-3ubuntu0.1_amd64.deb"
  ignore_errors: true

- name: Install smartmontools package
  apt:
    deb: "{{ FILE_PATH }}package_tool/smartmontools_7.2-1build2_amd64.deb"
  ignore_errors: true

- name: Install terminator package
  apt:
    deb: "{{ FILE_PATH }}package_tool/terminator_2.1.1-1_all.deb"
  ignore_errors: true

- name: Install vim package
  apt:
    deb: "{{ FILE_PATH }}package_tool/vim_2%3a8.2.3995-1ubuntu2.16_amd64.deb"
  ignore_errors: true

- name: Install fio package
  apt:
    deb: "{{ FILE_PATH }}package_tool/fio_3.28-1_amd64.deb"
  ignore_errors: true

- name: Install hdparm package
  apt:
    deb: "{{ FILE_PATH }}package_tool/hdparm_9.60+ds-1build3_amd64.deb"
  ignore_errors: true
