{
 "title": "1. Recipe(before machining)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X1\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Program",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X2\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recipe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X1\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "配方檢驗",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X1\"-\"X2\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "水溫即時值",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"D602\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "水溫配方值",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "content": "<table border=\"1\">\n<tr>\n<td style=\"height:150px;width:300px;\" align='center' valign=\"middle\"><font size=\"200\">50°C</font></td>\n</tr>\n</table>\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"D612\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "差值",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 50 -\"D602\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "近一小時水溫數據",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"D602\" FROM \"fx5u-100m\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "氣溫即時值",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"D602\" FROM \"fx5u-100m\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "氣溫配方值",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "content": "<table border=\"1\">\n<tr>\n<td style=\"height:150px;width:300px;\" align='center' valign=\"middle\"><font size=\"200\">55°C</font></td>\n</tr>\n</table>\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity_percent\" FROM \"Q02U\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "差值",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 55-\"temperature_C\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "近一小時氣溫數據",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature_C\" FROM \"Q02U\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X2\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "新液過熱",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "新液過熱",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X1\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "熱水過熱",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 16 },
   "targets": [
    {
     "alias": "熱水過熱",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"X2\" FROM \"Q02U\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "水洗低位",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "targets": [
    {
     "alias": "水洗低位",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M5\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "劑量低位",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 16 },
   "targets": [
    {
     "alias": "劑量低位",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M4\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "計量低位",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 16 },
   "targets": [
    {
     "alias": "計量低位",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M3\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "變頻異常",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 16 },
   "targets": [
    {
     "alias": "變頻異常",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M2\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "過載",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "過載",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M1\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "加熱器過熱",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 16 },
   "targets": [
    {
     "alias": "加熱器過熱",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "補液異常",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 16 },
   "targets": [
    {
     "alias": "補液異常",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "添加異常",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 16 },
   "targets": [
    {
     "alias": "添加異常",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"sample-device\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "噴霧過濾筒未關",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 16 },
   "targets": [
    {
     "alias": "噴霧過濾筒未關",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"fx5u-100m\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "新液洗門窗未關",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 16 },
   "targets": [
    {
     "alias": "新液洗門窗未關",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"sample-device\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}