{
 "title": "3. Alarm",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Level A Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M0\" FROM \"sample-device\" WHERE $timeFilter AND M0 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M1\" FROM \"sample-device\" WHERE $timeFilter AND M1 = 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Level B Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M2\" FROM \"sample-device\" WHERE $timeFilter AND M2 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M3\" FROM \"sample-device\" WHERE $timeFilter AND M3 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M4\" FROM \"sample-device\" WHERE $timeFilter AND M4 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Level C Alarm",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M5\" FROM \"sample-device\" WHERE $timeFilter AND M5 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"M6\" FROM \"sample-device\" WHERE $timeFilter AND M6 = 1 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "異常統計表(1 hour)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M0\")  as M0\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M0 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M1\")  as M1\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M1 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M2\")  as M2\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M2 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M3\")  as M3\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M3 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M4\")  as M4\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M4 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M5\")  as M5\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M5 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M6\")  as M6\nFROM\n    \"sample-device\"\nWHERE\n    $timeFilter AND\n    M6 = 1\nGROUP BY time(60m) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "異常統計表(8h)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M0\")  as M0\nFROM\n    \"sample-device\"\nWHERE\n    M0 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "< 8h", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M1\")  as M1\nFROM\n    \"sample-device\"\nWHERE\n    M1 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M2\")  as M2\nFROM\n    \"sample-device\"\nWHERE\n    M2 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M3\")  as M3\nFROM\n    \"sample-device\"\nWHERE\n    M3 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M4\")  as M4\nFROM\n    \"sample-device\"\nWHERE\n    M4 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M5\")  as M5\nFROM\n    \"sample-device\"\nWHERE\n    M5 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    COUNT(\"M6\")  as M6\nFROM\n    \"sample-device\"\nWHERE\n    M6 = 1\nGROUP BY time(8h) tz('Asia/Taipei')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}